name: Newman
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install report htmlextra
        run: npm install -g newman-reporter-htmlextra
      - name: Run newman
        run: newman run Products.postman_collection.json -e EnvironmentDev.postman_environment.json -g workspace.postman_globals.json -n 5 -r htmlextra
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./newman
